language: python

services:
  - docker

notifications:
  email: false

python:
  - "3.6"

env:
  matrix:
    - IMAGE=base-notebook
    - IMAGE=pangeo-notebook
  global:
    - DOCKER_ID=pangeo
    - CALVER="$( date '+%Y.%m.%d' )"

install:
  - pip install jupyter-repo2docker
  - repo2docker --version
  - docker version

before_script:
  # login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - IMAGE_NAME=${DOCKER_ID}/${IMAGE}:${CALVER}
  - echo "Building $IMAGE_NAME"
  # TODO: only push on master branch
  - repo2docker --push --no-run --user-name=jovyan --user-id 1000 --appendix="`cat appendix.txt`" --image-name=${IMAGE_NAME} ./${IMAGE}
  - echo "Done building/pushing $IMAGE_NAME"
