language: python

services:
  - docker

notifications:
  email: false

python:
  - "3.6"

env:
  matrix:
    - IMAGE=base-notebook
  global:
    - DOCKERHUB_ORG=pangeo
    - CALVER="$( date '+%Y.%m.%d.%H%M' )"

install:
  - pip install jupyter-repo2docker
  - repo2docker --version

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - IMAGE_NAME=${DOCKERHUB_ORG}/${IMAGE}:${CALVER}
  - repo2docker --push --debug --no-run --user-name=jovyan --user-id 1000 --appendix="`cat appendix.txt`" --image-name=${IMAGE_NAME} ./${IMAGE}
  # --push # Undocumented feature?
