language: python

services:
  - docker

notifications:
  email: false

python:
  - "3.6"

env:
  global:
    - IMAGE_PREFIX=pangeo/

install:
  - pip install --no-cache-dir -r requirements.txt
  - repo2docker --version
  - docker version

script:
  - python3 build.py --image-prefix=${IMAGE_PREFIX} base-notebook
  - python3 build.py --image-prefix=${IMAGE_PREFIX} pangeo-notebook

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

