language: python

services:
  - docker

notifications:
  email: false

python:
  - "3.6"

env:
  matrix:
    - IMAGE=base-notebook
    - IMAGE=pangeo-notebook
  global:
    - DOCKER_ID=pangeo
    - CALVER="$( date '+%Y.%m.%d' )"

install:
  - pip install jupyter-repo2docker
  - repo2docker --version
  - docker version

script:
  - IMAGE_NAME=${DOCKER_ID}/${IMAGE}:${CALVER}
  - IMAGE_LATEST=${DOCKER_ID}/${IMAGE}:latest
  - echo "Building ${IMAGE_NAME}"
  - repo2docker --no-run --user-name=jovyan --user-id 1000 --appendix="`cat appendix.txt`" --image-name=${IMAGE_NAME} ./${IMAGE}
  - echo "Done building ${IMAGE_NAME}"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
