language: python

services:
  - docker

notifications:
  email: false

python:
  - "3.6"

env:
  matrix:
    - IMAGE=base-notebook
    - IMAGE=pangeo-notebook
  global:
    - IMAGE_PREFIX=pangeo/

install:
  - pip install --no-cache-dir -r requirements.txt
  - repo2docker --version
  - docker version

script:
  - python3 build.py --image-prefix=${IMAGE_PREFIX} ${IMAGE}

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

