name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  # dask-related
  - dask
  - distributed
  - graphviz
  # pyviz
  - bokeh
  - holoviews
  - panel
  - geoviews
  - hvplot
  - geoviews
  - datashader
  # geospatial
  - cartopy
  - geopandas
  - rasterio
  - netcdf4
  # geoscience-relatedd
  - metpy
  - satpy
  - gsw
  - eofs
  - esmpy
  - xesmf
  - windspharm
  # intake-related
  - intake::intake
  - intake::intake-xarray
  - intake-esm
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - gcsfs
  - s3fs
  # jupyter-related
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyterhub
  - ipywidgets
  - ipyleaflet
  # xarray-related
  - xgcm
  - xrft
  - pip:
    - regionmask
    - git+https://github.com/dask/dask-labextension.git
