name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  - tensorflow
  - keras
  - pytorch-cpu
  # dask-related
  - dask
  - distributed
  - graphviz
  - kubernetes
  - dask-kubernetes
  - dask-jobqueue
  # pyviz
  - bokeh
  - holoviews
  - panel
  - geoviews
  - hvplot
  - geoviews
  - datashader
  - tornado
  # geospatial
  - iris
  - cartopy
  - geopandas
  - rasterio
  - netcdf4
  - h5py
  - h5netcdf
  # geoscience-related
  - climlab
  - metpy
  - satpy
  - gsw
  - eofs
  - esmpy
  - xesmf
  - windspharm
  # intake-related
  - intake
  - intake-xarray
  - intake-esm
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - gcsfs
  - s3fs
  # jupyter-related
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyterhub
  - ipywidgets
  - ipyleaflet
  # xarray-related
  - xgcm
  - xrft
  - pip:
    - regionmask
    - rio-cogeo
    - dask-labextension
