name: root
channels:
  - conda-forge
  - defaults
dependencies:
  - llvm
  - python=3.6
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - metpy
  - cmocean
  - basemap
  - proj4
  - pyresample
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - scipy
  - scikit-image
  - bokeh
  - pyviz/label/earthsim::holoviews
  - pyviz/label/earthsim::panel
  - geoviews
  - hvplot
  - rasterio>1.0.0
  - geoviews
  - datashader
  - gsw
  - kubernetes
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/zarr-developers/zarr.git
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/ContinuumIO/intake.git
    - graphviz
    - dask_labextension
    - nbgitpuller
