name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - jupyterlab=0.35
  - pip:
    - bokeh
    - dask-kubernetes
    - nbserverproxy
    - dask_labextension
    - ipywidgets