# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: pangeo
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.*
  - jupyterhub
  - nbgitpuller
  - dask>=2.2.0
  - distributed>=2.2.0
  - dask-kubernetes>=0.9.1
  - tornado=6.*
  - jupyter-server-proxy
  - bokeh
  - graphviz
  - pip
  - pip:
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
