name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab=1.0.1
  - jupyterhub
  # Pin tornado=5. Possible issues with bokeh & websockets?
  - tornado=5
  - bokeh
  - dask>=2.0.0
  - dask-kubernetes>=0.9.0
  - nbserverproxy
  - ipywidgets
  - graphviz
  - dask-labextension==1.0.0
