# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: pangeo
channels:
  - conda-forge
dependencies:
  - jupyterlab=1
  - jupyterhub=1
  - nbgitpuller=0.7
  - dask=2.4
  - distributed=2.4
  - dask-kubernetes=0.9.2
  - dask-gateway=0.3.0
  - tornado=6
  - jupyter-server-proxy=1.1
  - bokeh=1.3
  - graphviz=2.40
  - pip=19
  - pip:
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
