name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab=1.0.1
  - jupyterhub
  - tornado=6.0.3
  - bokeh
  - dask>=2.0.0
  - dask-kubernetes>=0.9.0
  - jupyter-server-proxy
  - ipywidgets
  - graphviz
  - pip
  - pip:
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
