name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - jupyterlab
  - jupyterhub
  - tornado=5.1.1
  - bokeh
  - dask>=2.0.0
  - dask-kubernetes>=0.9.0
  - nbserverproxy
  - ipywidgets
  - graphviz
  - dask-labextension==0.3.1
