name: build

on:
  push:
    branches:
      - master
    # Github tags (1.2.3) get corresponding dockerhub tag (DOCKER_IMAGE:1.2.3)
    tags:
      - '*'
    # paths:
    #   - binder/*
    #   - requirements.txt
  pull_request:
    branches:
      - master
    # paths:
    #   - binder/*
    #   - requirements.txt


env:
  CONTAINER_NAME: ${{ github.repository }} # user/repo format
  GITHUB_REF: ${{ github.ref }}
  IMAGE_PREFIX: pangeo/


jobs:
  base-notebook:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Enable Pip Cache
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        python --version
        pip install -r requirements.txt
        repo2docker --version
        docker version
    - name: Authenticate with DockerHub
      if: startswith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Image
      # Add folder of artifacts related to build that anyone can download
      run: |
        python3 build.py --image-prefix=${IMAGE_PREFIX} base-notebook
    - name: Push Image to DockerHub (latest & sha tags)
      # Only push if merge to master or pushed tag with v1.2.3 semantic version
      # if: github.ref == 'refs/heads/master'
      # Tag with short 7-character SHA
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA="$( git rev-parse --short HEAD )"
        DOCKER_TAG=${CALVER}-${SHA}
        echo $DOCKER_TAG
        echo docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:latest
    - name: Push Tagged Release Image to DockerHub
      # Only run this for 'git push --tags'
      # if: startswith(github.ref, 'refs/tags')
      run: |
        DOCKER_TAG=${GITHUB_REF##*/}
        echo docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:$DOCKER_TAG
  pangeo-notebook:
    needs: base-notebook
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Enable Pip Cache
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        python --version
        pip install -r requirements.txt
        repo2docker --version
        docker version
    - name: Authenticate with DockerHub
      if: startswith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Image
      # Add folder of artifacts related to build that anyone can download
      run: |
        python3 build.py --image-prefix=${IMAGE_PREFIX} pangeo-notebook
    - name: Push Image to DockerHub (latest & sha tags)
      # Only push if merge to master or pushed tag with v1.2.3 semantic version
      # if: github.ref == 'refs/heads/master'
      # Tag with short 7-character SHA
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA="$( git rev-parse --short HEAD )"
        DOCKER_TAG=${CALVER}-${SHA}
        echo $DOCKER_TAG
        echo docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:latest
    - name: Push Tagged Release Image to DockerHub
      # Only run this for 'git push --tags'
      # if: startswith(github.ref, 'refs/tags')
      run: |
        DOCKER_TAG=${GITHUB_REF##*/}
        echo docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:$DOCKER_TAG
  pangeo-esip:
    needs: base-notebook
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Enable Pip Cache
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        python --version
        pip install -r requirements.txt
        repo2docker --version
        docker version
    - name: Authenticate with DockerHub
      if: startswith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Image
      # Add folder of artifacts related to build that anyone can download
      run: |
        python3 build.py --image-prefix=${IMAGE_PREFIX} pangeo-esip
    - name: Push Image to DockerHub (latest & sha tags)
      # Only push if merge to master or pushed tag with v1.2.3 semantic version
      if: github.ref == 'refs/heads/master'
      # Tag with short 7-character SHA
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA="$( git rev-parse --short HEAD )"
        DOCKER_TAG=${CALVER}-${SHA}
        echo $DOCKER_TAG
        echo docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:latest
    - name: Push Tagged Release Image to DockerHub
      # Only run this for 'git push --tags'
      if: startswith(github.ref, 'refs/tags')
      run: |
        DOCKER_TAG=${GITHUB_REF##*/}
        echo docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:$DOCKER_TAG
        echo docker push $CONTAINER_NAME:$DOCKER_TAG